[
  {
    "success": false,
    "client_time": 0.013033866882324219,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bcf70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 0,
    "arrival_time": 1743455260.555835
  },
  {
    "success": false,
    "client_time": 0.006320476531982422,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bd960>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 1,
    "arrival_time": 1743455260.5799468
  },
  {
    "success": false,
    "client_time": 0.005736589431762695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bcdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 2,
    "arrival_time": 1743455260.7311928
  },
  {
    "success": false,
    "client_time": 0.0060825347900390625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be290>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 3,
    "arrival_time": 1743455261.0199165
  },
  {
    "success": false,
    "client_time": 0.005503177642822266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bec20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 4,
    "arrival_time": 1743455261.0671468
  },
  {
    "success": false,
    "client_time": 0.005795001983642578,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531420>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 5,
    "arrival_time": 1743455261.4562016
  },
  {
    "success": false,
    "client_time": 0.00467371940612793,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be500>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 6,
    "arrival_time": 1743455261.6198301
  },
  {
    "success": false,
    "client_time": 0.005426168441772461,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bdb70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 7,
    "arrival_time": 1743455261.7314065
  },
  {
    "success": false,
    "client_time": 0.005521535873413086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 8,
    "arrival_time": 1743455261.778197
  },
  {
    "success": false,
    "client_time": 0.006053447723388672,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfe20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 9,
    "arrival_time": 1743455261.9493458
  },
  {
    "success": false,
    "client_time": 0.0062601566314697266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfa30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 10,
    "arrival_time": 1743455261.975442
  },
  {
    "success": false,
    "client_time": 0.0064945220947265625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 11,
    "arrival_time": 1743455262.4153435
  },
  {
    "success": false,
    "client_time": 0.006192207336425781,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bdf30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 12,
    "arrival_time": 1743455262.4727378
  },
  {
    "success": false,
    "client_time": 0.0065839290618896484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 13,
    "arrival_time": 1743455262.7086089
  },
  {
    "success": false,
    "client_time": 0.0062253475189208984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 14,
    "arrival_time": 1743455262.9228892
  },
  {
    "success": false,
    "client_time": 0.005566596984863281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 15,
    "arrival_time": 1743455263.2250564
  },
  {
    "success": false,
    "client_time": 0.005820751190185547,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bde40>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 16,
    "arrival_time": 1743455263.6468928
  },
  {
    "success": false,
    "client_time": 0.005237102508544922,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc580>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 17,
    "arrival_time": 1743455263.971047
  },
  {
    "success": false,
    "client_time": 0.005426645278930664,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfd90>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 18,
    "arrival_time": 1743455264.1068034
  },
  {
    "success": false,
    "client_time": 0.009185075759887695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 19,
    "arrival_time": 1743455264.183115
  },
  {
    "success": false,
    "client_time": 0.006044626235961914,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfe20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 20,
    "arrival_time": 1743455264.6114893
  },
  {
    "success": false,
    "client_time": 0.005087137222290039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 21,
    "arrival_time": 1743455264.8712177
  },
  {
    "success": false,
    "client_time": 0.006448030471801758,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be350>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 22,
    "arrival_time": 1743455264.98503
  },
  {
    "success": false,
    "client_time": 0.006375551223754883,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bece0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 23,
    "arrival_time": 1743455265.1549625
  },
  {
    "success": false,
    "client_time": 0.007205486297607422,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532da0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 24,
    "arrival_time": 1743455265.201709
  },
  {
    "success": false,
    "client_time": 0.005120515823364258,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 25,
    "arrival_time": 1743455265.7464592
  },
  {
    "success": false,
    "client_time": 0.0053708553314208984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bde40>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 26,
    "arrival_time": 1743455266.2833188
  },
  {
    "success": false,
    "client_time": 0.005151271820068359,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc580>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 27,
    "arrival_time": 1743455266.3975382
  },
  {
    "success": false,
    "client_time": 0.005383729934692383,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 28,
    "arrival_time": 1743455266.4457443
  },
  {
    "success": false,
    "client_time": 0.005892276763916016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 29,
    "arrival_time": 1743455266.5630212
  },
  {
    "success": false,
    "client_time": 0.004822731018066406,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 30,
    "arrival_time": 1743455266.639021
  },
  {
    "success": false,
    "client_time": 0.005575418472290039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc580>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 31,
    "arrival_time": 1743455266.8541667
  },
  {
    "success": false,
    "client_time": 0.0062792301177978516,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be410>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 32,
    "arrival_time": 1743455267.1378546
  },
  {
    "success": false,
    "client_time": 0.006435394287109375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bece0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 33,
    "arrival_time": 1743455267.3684902
  },
  {
    "success": false,
    "client_time": 0.0057408809661865234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531420>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 34,
    "arrival_time": 1743455267.6689641
  },
  {
    "success": false,
    "client_time": 0.005103588104248047,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03beaa0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 35,
    "arrival_time": 1743455267.6845007
  },
  {
    "success": false,
    "client_time": 0.005669593811035156,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bdd80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 36,
    "arrival_time": 1743455267.7680562
  },
  {
    "success": false,
    "client_time": 0.006285190582275391,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bcf70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 37,
    "arrival_time": 1743455267.9445293
  },
  {
    "success": false,
    "client_time": 0.006426811218261719,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 38,
    "arrival_time": 1743455267.987874
  },
  {
    "success": false,
    "client_time": 0.007505178451538086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 39,
    "arrival_time": 1743455268.336956
  },
  {
    "success": false,
    "client_time": 0.006436824798583984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bed10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 40,
    "arrival_time": 1743455268.5904574
  },
  {
    "success": false,
    "client_time": 0.005217075347900391,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 41,
    "arrival_time": 1743455268.6126676
  },
  {
    "success": false,
    "client_time": 0.005890846252441406,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be620>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 42,
    "arrival_time": 1743455268.8575373
  },
  {
    "success": false,
    "client_time": 0.007864713668823242,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc640>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 43,
    "arrival_time": 1743455269.0325816
  },
  {
    "success": false,
    "client_time": 0.005563497543334961,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25313f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 44,
    "arrival_time": 1743455269.175415
  },
  {
    "success": false,
    "client_time": 0.005517244338989258,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be980>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 45,
    "arrival_time": 1743455269.7032936
  },
  {
    "success": false,
    "client_time": 0.00601649284362793,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bd150>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 46,
    "arrival_time": 1743455269.8248963
  },
  {
    "success": false,
    "client_time": 0.005442380905151367,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 47,
    "arrival_time": 1743455270.0708983
  },
  {
    "success": false,
    "client_time": 0.006731271743774414,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfd30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 48,
    "arrival_time": 1743455270.0942771
  },
  {
    "success": false,
    "client_time": 0.006379842758178711,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533c70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 49,
    "arrival_time": 1743455270.3558264
  },
  {
    "success": false,
    "client_time": 0.005719900131225586,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 50,
    "arrival_time": 1743455270.4326937
  },
  {
    "success": false,
    "client_time": 0.0036618709564208984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bf580>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 51,
    "arrival_time": 1743455270.575464
  },
  {
    "success": false,
    "client_time": 0.005636453628540039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 52,
    "arrival_time": 1743455270.7082055
  },
  {
    "success": false,
    "client_time": 0.005688190460205078,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25589a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 53,
    "arrival_time": 1743455270.7276447
  },
  {
    "success": false,
    "client_time": 0.0058324337005615234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 54,
    "arrival_time": 1743455271.0077245
  },
  {
    "success": false,
    "client_time": 0.006445407867431641,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 55,
    "arrival_time": 1743455271.0694933
  },
  {
    "success": false,
    "client_time": 0.005520343780517578,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 56,
    "arrival_time": 1743455271.4114048
  },
  {
    "success": false,
    "client_time": 0.005432844161987305,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfd60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 57,
    "arrival_time": 1743455271.4430122
  },
  {
    "success": false,
    "client_time": 0.0066792964935302734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532200>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 58,
    "arrival_time": 1743455272.1849563
  },
  {
    "success": false,
    "client_time": 0.006120204925537109,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 59,
    "arrival_time": 1743455272.215609
  },
  {
    "success": false,
    "client_time": 0.0059545040130615234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 60,
    "arrival_time": 1743455272.38065
  },
  {
    "success": false,
    "client_time": 0.00778961181640625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfe80>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 61,
    "arrival_time": 1743455272.3831756
  },
  {
    "success": false,
    "client_time": 0.004510641098022461,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be440>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 62,
    "arrival_time": 1743455272.4393294
  },
  {
    "success": false,
    "client_time": 0.006281375885009766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25588b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 63,
    "arrival_time": 1743455272.5926795
  },
  {
    "success": false,
    "client_time": 0.005148649215698242,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25313f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 64,
    "arrival_time": 1743455272.6510687
  },
  {
    "success": false,
    "client_time": 0.0050046443939208984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532a70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 65,
    "arrival_time": 1743455272.859992
  },
  {
    "success": false,
    "client_time": 0.005598545074462891,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 66,
    "arrival_time": 1743455273.5404618
  },
  {
    "success": false,
    "client_time": 0.006148099899291992,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc670>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 67,
    "arrival_time": 1743455273.613164
  },
  {
    "success": false,
    "client_time": 0.0071828365325927734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532b60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 68,
    "arrival_time": 1743455273.6841714
  },
  {
    "success": false,
    "client_time": 0.005741119384765625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25334f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 69,
    "arrival_time": 1743455273.850255
  },
  {
    "success": false,
    "client_time": 0.00589299201965332,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 70,
    "arrival_time": 1743455273.9648056
  },
  {
    "success": false,
    "client_time": 0.005292177200317383,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bf970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 71,
    "arrival_time": 1743455274.053924
  },
  {
    "success": false,
    "client_time": 0.005807161331176758,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bcdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 72,
    "arrival_time": 1743455274.2297473
  },
  {
    "success": false,
    "client_time": 0.007484912872314453,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558a60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 73,
    "arrival_time": 1743455274.8941298
  },
  {
    "success": false,
    "client_time": 0.0054073333740234375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 74,
    "arrival_time": 1743455274.9212687
  },
  {
    "success": false,
    "client_time": 0.005998849868774414,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531f60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 75,
    "arrival_time": 1743455274.9254408
  },
  {
    "success": false,
    "client_time": 0.006122112274169922,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bf7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 76,
    "arrival_time": 1743455275.171661
  },
  {
    "success": false,
    "client_time": 0.007662534713745117,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bddb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 77,
    "arrival_time": 1743455275.3011014
  },
  {
    "success": false,
    "client_time": 0.0038080215454101562,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25334f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 78,
    "arrival_time": 1743455275.5604699
  },
  {
    "success": false,
    "client_time": 0.006283283233642578,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25595a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 79,
    "arrival_time": 1743455275.807828
  },
  {
    "success": false,
    "client_time": 0.0058629512786865234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559120>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 80,
    "arrival_time": 1743455275.8306289
  },
  {
    "success": false,
    "client_time": 0.005633831024169922,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfd90>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 81,
    "arrival_time": 1743455276.0861676
  },
  {
    "success": false,
    "client_time": 0.0073566436767578125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be800>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 82,
    "arrival_time": 1743455276.4032824
  },
  {
    "success": false,
    "client_time": 0.006079435348510742,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558b20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 83,
    "arrival_time": 1743455276.9125836
  },
  {
    "success": false,
    "client_time": 0.0058100223541259766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25327a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 84,
    "arrival_time": 1743455277.0168238
  },
  {
    "success": false,
    "client_time": 0.0054056644439697266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532a70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 85,
    "arrival_time": 1743455277.0469582
  },
  {
    "success": false,
    "client_time": 0.005758523941040039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bf790>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 86,
    "arrival_time": 1743455277.4588933
  },
  {
    "success": false,
    "client_time": 0.006941080093383789,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531990>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 87,
    "arrival_time": 1743455277.6040046
  },
  {
    "success": false,
    "client_time": 0.003203868865966797,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 88,
    "arrival_time": 1743455277.6154666
  },
  {
    "success": false,
    "client_time": 0.006078004837036133,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 89,
    "arrival_time": 1743455277.8526852
  },
  {
    "success": false,
    "client_time": 0.005854129791259766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 90,
    "arrival_time": 1743455278.4853258
  },
  {
    "success": false,
    "client_time": 0.005674600601196289,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc550>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 91,
    "arrival_time": 1743455278.7126284
  },
  {
    "success": false,
    "client_time": 0.008216142654418945,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558370>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 92,
    "arrival_time": 1743455279.0216992
  },
  {
    "success": false,
    "client_time": 0.005744218826293945,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559a20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 93,
    "arrival_time": 1743455279.0672584
  },
  {
    "success": false,
    "client_time": 0.005257129669189453,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 94,
    "arrival_time": 1743455279.523377
  },
  {
    "success": false,
    "client_time": 0.005275249481201172,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531c90>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 95,
    "arrival_time": 1743455280.2171307
  },
  {
    "success": false,
    "client_time": 0.005169868469238281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 96,
    "arrival_time": 1743455280.2284274
  },
  {
    "success": false,
    "client_time": 0.005818605422973633,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25336a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 97,
    "arrival_time": 1743455280.3063047
  },
  {
    "success": false,
    "client_time": 0.008160114288330078,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a260>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 98,
    "arrival_time": 1743455280.7335014
  },
  {
    "success": false,
    "client_time": 0.009076118469238281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a530>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 99,
    "arrival_time": 1743455280.7352886
  },
  {
    "success": false,
    "client_time": 0.005480527877807617,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558820>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 100,
    "arrival_time": 1743455280.8270767
  },
  {
    "success": false,
    "client_time": 0.0043256282806396484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc550>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 101,
    "arrival_time": 1743455281.2911606
  },
  {
    "success": false,
    "client_time": 0.005900859832763672,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 102,
    "arrival_time": 1743455281.3004198
  },
  {
    "success": false,
    "client_time": 0.00599217414855957,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255ada0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 103,
    "arrival_time": 1743455281.7776904
  },
  {
    "success": false,
    "client_time": 0.0063364505767822266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 104,
    "arrival_time": 1743455282.0394242
  },
  {
    "success": false,
    "client_time": 0.00598907470703125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 105,
    "arrival_time": 1743455282.2043412
  },
  {
    "success": false,
    "client_time": 0.0060482025146484375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bd210>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 106,
    "arrival_time": 1743455282.4682362
  },
  {
    "success": false,
    "client_time": 0.005556821823120117,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25330a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 107,
    "arrival_time": 1743455282.4936314
  },
  {
    "success": false,
    "client_time": 0.005574464797973633,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25593f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 108,
    "arrival_time": 1743455282.5254314
  },
  {
    "success": false,
    "client_time": 0.0053861141204833984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 109,
    "arrival_time": 1743455282.9993885
  },
  {
    "success": false,
    "client_time": 0.005554914474487305,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a830>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 110,
    "arrival_time": 1743455283.246416
  },
  {
    "success": false,
    "client_time": 0.006494760513305664,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bcf70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 111,
    "arrival_time": 1743455283.5599027
  },
  {
    "success": false,
    "client_time": 0.0051839351654052734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558f70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 112,
    "arrival_time": 1743455283.5758333
  },
  {
    "success": false,
    "client_time": 0.005831241607666016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 113,
    "arrival_time": 1743455283.656291
  },
  {
    "success": false,
    "client_time": 0.005134105682373047,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25594e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 114,
    "arrival_time": 1743455283.8617978
  },
  {
    "success": false,
    "client_time": 0.005018711090087891,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25338b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 115,
    "arrival_time": 1743455284.7006114
  },
  {
    "success": false,
    "client_time": 0.0068950653076171875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25319c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 116,
    "arrival_time": 1743455285.055199
  },
  {
    "success": false,
    "client_time": 0.0062062740325927734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b160>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 117,
    "arrival_time": 1743455285.7802162
  },
  {
    "success": false,
    "client_time": 0.005672454833984375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 118,
    "arrival_time": 1743455285.9490578
  },
  {
    "success": false,
    "client_time": 0.004967212677001953,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 119,
    "arrival_time": 1743455286.4268367
  },
  {
    "success": false,
    "client_time": 0.006108522415161133,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc268f2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 120,
    "arrival_time": 1743455286.4924905
  },
  {
    "success": false,
    "client_time": 0.005880594253540039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25596f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 121,
    "arrival_time": 1743455286.5185518
  },
  {
    "success": false,
    "client_time": 0.005425930023193359,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558b20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 122,
    "arrival_time": 1743455286.6245499
  },
  {
    "success": false,
    "client_time": 0.006366252899169922,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 123,
    "arrival_time": 1743455286.7733862
  },
  {
    "success": false,
    "client_time": 0.006433010101318359,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 124,
    "arrival_time": 1743455286.7965195
  },
  {
    "success": false,
    "client_time": 0.006618499755859375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 125,
    "arrival_time": 1743455287.2766721
  },
  {
    "success": false,
    "client_time": 0.006216287612915039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532230>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 126,
    "arrival_time": 1743455287.2866251
  },
  {
    "success": false,
    "client_time": 0.005246877670288086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 127,
    "arrival_time": 1743455287.3186803
  },
  {
    "success": false,
    "client_time": 0.0056722164154052734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 128,
    "arrival_time": 1743455287.4315426
  },
  {
    "success": false,
    "client_time": 0.00516057014465332,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 129,
    "arrival_time": 1743455287.4404638
  },
  {
    "success": false,
    "client_time": 0.005424976348876953,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558d60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 130,
    "arrival_time": 1743455287.52912
  },
  {
    "success": false,
    "client_time": 0.006868600845336914,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25585e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 131,
    "arrival_time": 1743455287.5471687
  },
  {
    "success": false,
    "client_time": 0.005356311798095703,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255bee0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 132,
    "arrival_time": 1743455287.7169826
  },
  {
    "success": false,
    "client_time": 0.004696846008300781,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25591e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 133,
    "arrival_time": 1743455287.9481094
  },
  {
    "success": false,
    "client_time": 0.005448579788208008,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 134,
    "arrival_time": 1743455288.065911
  },
  {
    "success": false,
    "client_time": 0.007055521011352539,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533a60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 135,
    "arrival_time": 1743455288.1105113
  },
  {
    "success": false,
    "client_time": 0.0044629573822021484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 136,
    "arrival_time": 1743455288.5354538
  },
  {
    "success": false,
    "client_time": 0.006016254425048828,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 137,
    "arrival_time": 1743455288.8780508
  },
  {
    "success": false,
    "client_time": 0.006076335906982422,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 138,
    "arrival_time": 1743455289.3476372
  },
  {
    "success": false,
    "client_time": 0.004845142364501953,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 139,
    "arrival_time": 1743455289.412377
  },
  {
    "success": false,
    "client_time": 0.007695198059082031,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03be890>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 140,
    "arrival_time": 1743455289.4890125
  },
  {
    "success": false,
    "client_time": 0.005051851272583008,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 141,
    "arrival_time": 1743455289.7094483
  },
  {
    "success": false,
    "client_time": 0.0065004825592041016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a230>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 142,
    "arrival_time": 1743455289.8610303
  },
  {
    "success": false,
    "client_time": 0.005644559860229492,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25589a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 143,
    "arrival_time": 1743455289.8931181
  },
  {
    "success": false,
    "client_time": 0.0055694580078125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 144,
    "arrival_time": 1743455289.9516616
  },
  {
    "success": false,
    "client_time": 0.00781559944152832,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 145,
    "arrival_time": 1743455290.6397936
  },
  {
    "success": false,
    "client_time": 0.005353689193725586,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25313f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 146,
    "arrival_time": 1743455290.653831
  },
  {
    "success": false,
    "client_time": 0.004869222640991211,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255ba30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 147,
    "arrival_time": 1743455290.7387288
  },
  {
    "success": false,
    "client_time": 0.005340576171875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b130>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 148,
    "arrival_time": 1743455290.7577567
  },
  {
    "success": false,
    "client_time": 0.005434274673461914,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a530>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 149,
    "arrival_time": 1743455290.7958064
  },
  {
    "success": false,
    "client_time": 0.007093191146850586,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 150,
    "arrival_time": 1743455291.0868149
  },
  {
    "success": false,
    "client_time": 0.005503654479980469,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 151,
    "arrival_time": 1743455291.4377825
  },
  {
    "success": false,
    "client_time": 0.0052967071533203125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25587f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 152,
    "arrival_time": 1743455291.4855773
  },
  {
    "success": false,
    "client_time": 0.0053026676177978516,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559c60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 153,
    "arrival_time": 1743455291.5124862
  },
  {
    "success": false,
    "client_time": 0.006008148193359375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 154,
    "arrival_time": 1743455291.5688252
  },
  {
    "success": false,
    "client_time": 0.006134510040283203,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ceb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 155,
    "arrival_time": 1743455291.6555617
  },
  {
    "success": false,
    "client_time": 0.00553584098815918,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559e70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 156,
    "arrival_time": 1743455291.812972
  },
  {
    "success": false,
    "client_time": 0.004999876022338867,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559660>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 157,
    "arrival_time": 1743455291.8594315
  },
  {
    "success": false,
    "client_time": 0.006067037582397461,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25585b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 158,
    "arrival_time": 1743455291.9247708
  },
  {
    "success": false,
    "client_time": 0.005034923553466797,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559960>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 159,
    "arrival_time": 1743455291.9853153
  },
  {
    "success": false,
    "client_time": 0.0056226253509521484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 160,
    "arrival_time": 1743455292.4382699
  },
  {
    "success": false,
    "client_time": 0.005358695983886719,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255ace0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 161,
    "arrival_time": 1743455292.5044246
  },
  {
    "success": false,
    "client_time": 0.005662679672241211,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559630>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 162,
    "arrival_time": 1743455292.6954556
  },
  {
    "success": false,
    "client_time": 0.0056264400482177734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 163,
    "arrival_time": 1743455292.7047458
  },
  {
    "success": false,
    "client_time": 0.005666017532348633,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c520>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 164,
    "arrival_time": 1743455292.7601554
  },
  {
    "success": false,
    "client_time": 0.0056917667388916016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a260>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 165,
    "arrival_time": 1743455292.851383
  },
  {
    "success": false,
    "client_time": 0.005948305130004883,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b430>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 166,
    "arrival_time": 1743455292.8756926
  },
  {
    "success": false,
    "client_time": 0.00486302375793457,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25591b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 167,
    "arrival_time": 1743455293.0993817
  },
  {
    "success": false,
    "client_time": 0.005112886428833008,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dea0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 168,
    "arrival_time": 1743455293.2329984
  },
  {
    "success": false,
    "client_time": 0.006684303283691406,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ddb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 169,
    "arrival_time": 1743455293.4108818
  },
  {
    "success": false,
    "client_time": 0.006056547164916992,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558f70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 170,
    "arrival_time": 1743455293.5044277
  },
  {
    "success": false,
    "client_time": 0.005566596984863281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25589a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 171,
    "arrival_time": 1743455293.5396097
  },
  {
    "success": false,
    "client_time": 0.006450653076171875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 172,
    "arrival_time": 1743455293.6710384
  },
  {
    "success": false,
    "client_time": 0.005103349685668945,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d060>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 173,
    "arrival_time": 1743455293.9295492
  },
  {
    "success": false,
    "client_time": 0.005928993225097656,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533370>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 174,
    "arrival_time": 1743455294.0043967
  },
  {
    "success": false,
    "client_time": 0.005695343017578125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a260>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 175,
    "arrival_time": 1743455294.6848245
  },
  {
    "success": false,
    "client_time": 0.005765438079833984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 176,
    "arrival_time": 1743455294.707421
  },
  {
    "success": false,
    "client_time": 0.004361629486083984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558be0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 177,
    "arrival_time": 1743455294.7554717
  },
  {
    "success": false,
    "client_time": 0.009665727615356445,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bdf00>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 178,
    "arrival_time": 1743455294.8205278
  },
  {
    "success": false,
    "client_time": 0.009628057479858398,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25583a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 179,
    "arrival_time": 1743455294.8211806
  },
  {
    "success": false,
    "client_time": 0.00529026985168457,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559c60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 180,
    "arrival_time": 1743455295.3550966
  },
  {
    "success": false,
    "client_time": 0.005629777908325195,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 181,
    "arrival_time": 1743455295.4014103
  },
  {
    "success": false,
    "client_time": 0.005391597747802734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d7e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 182,
    "arrival_time": 1743455296.277222
  },
  {
    "success": false,
    "client_time": 0.005472898483276367,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc03bc8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 183,
    "arrival_time": 1743455296.5204313
  },
  {
    "success": false,
    "client_time": 0.006268024444580078,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257df30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 184,
    "arrival_time": 1743455296.6790893
  },
  {
    "success": false,
    "client_time": 0.006711483001708984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25333a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 185,
    "arrival_time": 1743455297.0726113
  },
  {
    "success": false,
    "client_time": 0.006353616714477539,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 186,
    "arrival_time": 1743455297.4683669
  },
  {
    "success": false,
    "client_time": 0.005964040756225586,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 187,
    "arrival_time": 1743455297.5746408
  },
  {
    "success": false,
    "client_time": 0.007353305816650391,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 188,
    "arrival_time": 1743455298.0539746
  },
  {
    "success": false,
    "client_time": 0.00548100471496582,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ee60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 189,
    "arrival_time": 1743455298.1928687
  },
  {
    "success": false,
    "client_time": 0.00567626953125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d7e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 190,
    "arrival_time": 1743455298.3655055
  },
  {
    "success": false,
    "client_time": 0.005234718322753906,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559720>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 191,
    "arrival_time": 1743455298.3863592
  },
  {
    "success": false,
    "client_time": 0.0062406063079833984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558430>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 192,
    "arrival_time": 1743455298.8832526
  },
  {
    "success": false,
    "client_time": 0.00782155990600586,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255b760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 193,
    "arrival_time": 1743455299.3506615
  },
  {
    "success": false,
    "client_time": 0.006013631820678711,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dcf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 194,
    "arrival_time": 1743455299.3599613
  },
  {
    "success": false,
    "client_time": 0.0053675174713134766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257df60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 195,
    "arrival_time": 1743455299.4893572
  },
  {
    "success": false,
    "client_time": 0.006528615951538086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dc30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 196,
    "arrival_time": 1743455300.1571982
  },
  {
    "success": false,
    "client_time": 0.00530552864074707,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2559870>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 197,
    "arrival_time": 1743455300.3099327
  },
  {
    "success": false,
    "client_time": 0.00830221176147461,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 198,
    "arrival_time": 1743455301.023841
  },
  {
    "success": false,
    "client_time": 0.005287647247314453,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257e020>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 199,
    "arrival_time": 1743455301.6021447
  },
  {
    "success": false,
    "client_time": 0.006369829177856445,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dea0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 200,
    "arrival_time": 1743455301.9979606
  },
  {
    "success": false,
    "client_time": 0.005588531494140625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25316f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 201,
    "arrival_time": 1743455302.3886943
  },
  {
    "success": false,
    "client_time": 0.005396366119384766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 202,
    "arrival_time": 1743455302.4394345
  },
  {
    "success": false,
    "client_time": 0.0072596073150634766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 203,
    "arrival_time": 1743455302.595697
  },
  {
    "success": false,
    "client_time": 0.005277395248413086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f520>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 204,
    "arrival_time": 1743455302.6489806
  },
  {
    "success": false,
    "client_time": 0.006092548370361328,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257eaa0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 205,
    "arrival_time": 1743455302.875764
  },
  {
    "success": false,
    "client_time": 0.005383491516113281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 206,
    "arrival_time": 1743455302.9070528
  },
  {
    "success": false,
    "client_time": 0.004601240158081055,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 207,
    "arrival_time": 1743455302.9336379
  },
  {
    "success": false,
    "client_time": 0.006233692169189453,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257cca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 208,
    "arrival_time": 1743455303.0590515
  },
  {
    "success": false,
    "client_time": 0.0055506229400634766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d870>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 209,
    "arrival_time": 1743455303.0724142
  },
  {
    "success": false,
    "client_time": 0.006085872650146484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d1e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 210,
    "arrival_time": 1743455303.6382186
  },
  {
    "success": false,
    "client_time": 0.005769491195678711,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 211,
    "arrival_time": 1743455303.7756307
  },
  {
    "success": false,
    "client_time": 0.006532192230224609,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 212,
    "arrival_time": 1743455303.9521217
  },
  {
    "success": false,
    "client_time": 0.008291482925415039,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533e20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 213,
    "arrival_time": 1743455304.1558146
  },
  {
    "success": false,
    "client_time": 0.006044149398803711,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f520>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 214,
    "arrival_time": 1743455304.3329182
  },
  {
    "success": false,
    "client_time": 0.0057451725006103516,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257eaa0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 215,
    "arrival_time": 1743455304.3739386
  },
  {
    "success": false,
    "client_time": 0.005471944808959961,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d2a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 216,
    "arrival_time": 1743455305.2570956
  },
  {
    "success": false,
    "client_time": 0.004027366638183594,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25580a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 217,
    "arrival_time": 1743455305.5242755
  },
  {
    "success": false,
    "client_time": 0.0061626434326171875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d720>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 218,
    "arrival_time": 1743455305.6185756
  },
  {
    "success": false,
    "client_time": 0.004408597946166992,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 219,
    "arrival_time": 1743455306.0096939
  },
  {
    "success": false,
    "client_time": 0.004294157028198242,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 220,
    "arrival_time": 1743455306.1004245
  },
  {
    "success": false,
    "client_time": 0.005894660949707031,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 221,
    "arrival_time": 1743455306.144592
  },
  {
    "success": false,
    "client_time": 0.007418155670166016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc255a7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 222,
    "arrival_time": 1743455306.2595942
  },
  {
    "success": false,
    "client_time": 0.006706714630126953,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257fbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 223,
    "arrival_time": 1743455306.2634592
  },
  {
    "success": false,
    "client_time": 0.006144285202026367,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d330>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 224,
    "arrival_time": 1743455306.3006673
  },
  {
    "success": false,
    "client_time": 0.006314754486083984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257e020>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 225,
    "arrival_time": 1743455306.4098043
  },
  {
    "success": false,
    "client_time": 0.004762172698974609,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d870>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 226,
    "arrival_time": 1743455306.4582932
  },
  {
    "success": false,
    "client_time": 0.005955696105957031,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2558070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 227,
    "arrival_time": 1743455306.52849
  },
  {
    "success": false,
    "client_time": 0.006104469299316406,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257e830>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 228,
    "arrival_time": 1743455306.590924
  },
  {
    "success": false,
    "client_time": 0.005217790603637695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f970>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 229,
    "arrival_time": 1743455306.6414704
  },
  {
    "success": false,
    "client_time": 0.006413936614990234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d660>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 230,
    "arrival_time": 1743455306.8104901
  },
  {
    "success": false,
    "client_time": 0.006458282470703125,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 231,
    "arrival_time": 1743455307.103302
  },
  {
    "success": false,
    "client_time": 0.0067369937896728516,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25331f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 232,
    "arrival_time": 1743455307.1212351
  },
  {
    "success": false,
    "client_time": 0.005614280700683594,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f130>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 233,
    "arrival_time": 1743455307.1550531
  },
  {
    "success": false,
    "client_time": 0.005642414093017578,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 234,
    "arrival_time": 1743455307.2562315
  },
  {
    "success": false,
    "client_time": 0.00635981559753418,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257e9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 235,
    "arrival_time": 1743455307.6289158
  },
  {
    "success": false,
    "client_time": 0.006041765213012695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 236,
    "arrival_time": 1743455307.6854775
  },
  {
    "success": false,
    "client_time": 0.008342504501342773,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 237,
    "arrival_time": 1743455308.4494588
  },
  {
    "success": false,
    "client_time": 0.00626373291015625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257e830>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 238,
    "arrival_time": 1743455308.539895
  },
  {
    "success": false,
    "client_time": 0.005694150924682617,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dcf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 239,
    "arrival_time": 1743455308.5901978
  },
  {
    "success": false,
    "client_time": 0.0064580440521240234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dd20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 240,
    "arrival_time": 1743455308.7499268
  },
  {
    "success": false,
    "client_time": 0.005081892013549805,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039ca60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 241,
    "arrival_time": 1743455308.9829698
  },
  {
    "success": false,
    "client_time": 0.00657963752746582,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039cca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 242,
    "arrival_time": 1743455309.1174278
  },
  {
    "success": false,
    "client_time": 0.005543708801269531,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 243,
    "arrival_time": 1743455309.277207
  },
  {
    "success": false,
    "client_time": 0.006101369857788086,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ece0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 244,
    "arrival_time": 1743455309.4708128
  },
  {
    "success": false,
    "client_time": 0.005539894104003906,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ee60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 245,
    "arrival_time": 1743455309.5892744
  },
  {
    "success": false,
    "client_time": 0.0055389404296875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257fe20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 246,
    "arrival_time": 1743455309.6418192
  },
  {
    "success": false,
    "client_time": 0.006850719451904297,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039ce20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 247,
    "arrival_time": 1743455309.9287825
  },
  {
    "success": false,
    "client_time": 0.005339860916137695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039ca30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 248,
    "arrival_time": 1743455310.0331042
  },
  {
    "success": false,
    "client_time": 0.006070137023925781,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dae0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 249,
    "arrival_time": 1743455310.2260306
  },
  {
    "success": false,
    "client_time": 0.005324602127075195,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dab0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 250,
    "arrival_time": 1743455310.3704126
  },
  {
    "success": false,
    "client_time": 0.006049156188964844,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257fbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 251,
    "arrival_time": 1743455310.7144399
  },
  {
    "success": false,
    "client_time": 0.007730960845947266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d8a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 252,
    "arrival_time": 1743455310.9256947
  },
  {
    "success": false,
    "client_time": 0.006404399871826172,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 253,
    "arrival_time": 1743455311.0645452
  },
  {
    "success": false,
    "client_time": 0.005636930465698242,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257df60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 254,
    "arrival_time": 1743455311.1165128
  },
  {
    "success": false,
    "client_time": 0.005909919738769531,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d120>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 255,
    "arrival_time": 1743455311.3723412
  },
  {
    "success": false,
    "client_time": 0.007452249526977539,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d870>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 256,
    "arrival_time": 1743455311.4438138
  },
  {
    "success": false,
    "client_time": 0.004711627960205078,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c520>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 257,
    "arrival_time": 1743455311.521154
  },
  {
    "success": false,
    "client_time": 0.005614519119262695,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c820>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 258,
    "arrival_time": 1743455311.5929556
  },
  {
    "success": false,
    "client_time": 0.005597114562988281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dcf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 259,
    "arrival_time": 1743455312.0760088
  },
  {
    "success": false,
    "client_time": 0.005170345306396484,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257c730>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 260,
    "arrival_time": 1743455312.3210404
  },
  {
    "success": false,
    "client_time": 0.007428169250488281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2532bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 261,
    "arrival_time": 1743455312.4818718
  },
  {
    "success": false,
    "client_time": 0.006400585174560547,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257cb20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 262,
    "arrival_time": 1743455312.6617064
  },
  {
    "success": false,
    "client_time": 0.00478053092956543,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 263,
    "arrival_time": 1743455312.9447324
  },
  {
    "success": false,
    "client_time": 0.0052165985107421875,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 264,
    "arrival_time": 1743455313.025514
  },
  {
    "success": false,
    "client_time": 0.005768775939941406,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 265,
    "arrival_time": 1743455313.1130993
  },
  {
    "success": false,
    "client_time": 0.006279468536376953,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 266,
    "arrival_time": 1743455313.365459
  },
  {
    "success": false,
    "client_time": 0.005391120910644531,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 267,
    "arrival_time": 1743455313.517003
  },
  {
    "success": false,
    "client_time": 0.005462169647216797,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039dc60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 268,
    "arrival_time": 1743455313.6077368
  },
  {
    "success": false,
    "client_time": 0.004574775695800781,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 269,
    "arrival_time": 1743455313.8513153
  },
  {
    "success": false,
    "client_time": 0.005728244781494141,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f460>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 270,
    "arrival_time": 1743455314.093675
  },
  {
    "success": false,
    "client_time": 0.006543159484863281,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2533c70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 271,
    "arrival_time": 1743455314.207772
  },
  {
    "success": false,
    "client_time": 0.005741119384765625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039e6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 272,
    "arrival_time": 1743455314.5371866
  },
  {
    "success": false,
    "client_time": 0.0063588619232177734,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039dea0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 273,
    "arrival_time": 1743455314.7470787
  },
  {
    "success": false,
    "client_time": 0.006052494049072266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 274,
    "arrival_time": 1743455315.0284388
  },
  {
    "success": false,
    "client_time": 0.005099296569824219,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ebf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 275,
    "arrival_time": 1743455315.1424806
  },
  {
    "success": false,
    "client_time": 0.006063938140869141,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d030>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 276,
    "arrival_time": 1743455315.6768594
  },
  {
    "success": false,
    "client_time": 0.005655527114868164,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039e0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 277,
    "arrival_time": 1743455315.7587583
  },
  {
    "success": false,
    "client_time": 0.004888772964477539,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039dae0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 278,
    "arrival_time": 1743455315.8587317
  },
  {
    "success": false,
    "client_time": 0.0057260990142822266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc2531990>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 279,
    "arrival_time": 1743455315.864867
  },
  {
    "success": false,
    "client_time": 0.005955934524536133,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257dd20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 280,
    "arrival_time": 1743455315.948205
  },
  {
    "success": false,
    "client_time": 0.006772518157958984,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25327d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 281,
    "arrival_time": 1743455316.416031
  },
  {
    "success": false,
    "client_time": 0.0056955814361572266,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039e8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 282,
    "arrival_time": 1743455316.7359478
  },
  {
    "success": false,
    "client_time": 0.006472110748291016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039dea0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 283,
    "arrival_time": 1743455317.5536695
  },
  {
    "success": false,
    "client_time": 0.005945682525634766,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039ea70>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 284,
    "arrival_time": 1743455317.640998
  },
  {
    "success": false,
    "client_time": 0.006536722183227539,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257ebf0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 285,
    "arrival_time": 1743455317.9296052
  },
  {
    "success": false,
    "client_time": 0.007442474365234375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 286,
    "arrival_time": 1743455318.275547
  },
  {
    "success": false,
    "client_time": 0.006205320358276367,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039f0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 287,
    "arrival_time": 1743455318.3882928
  },
  {
    "success": false,
    "client_time": 0.005495548248291016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039e5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 288,
    "arrival_time": 1743455318.8157055
  },
  {
    "success": false,
    "client_time": 0.0051517486572265625,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25333a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 289,
    "arrival_time": 1743455318.8219335
  },
  {
    "success": false,
    "client_time": 0.008355379104614258,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257d4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 290,
    "arrival_time": 1743455319.04886
  },
  {
    "success": false,
    "client_time": 0.005705356597900391,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039f5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 291,
    "arrival_time": 1743455319.1498497
  },
  {
    "success": false,
    "client_time": 0.006166934967041016,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039ca30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 292,
    "arrival_time": 1743455319.3336983
  },
  {
    "success": false,
    "client_time": 0.0059108734130859375,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d1e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 293,
    "arrival_time": 1743455319.3732896
  },
  {
    "success": false,
    "client_time": 0.006234645843505859,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039d6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 294,
    "arrival_time": 1743455319.3999588
  },
  {
    "success": false,
    "client_time": 0.007122516632080078,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc257f070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 295,
    "arrival_time": 1743455320.040967
  },
  {
    "success": false,
    "client_time": 0.0067632198333740234,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039fa30>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 296,
    "arrival_time": 1743455320.2749975
  },
  {
    "success": false,
    "client_time": 0.005784273147583008,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 297,
    "arrival_time": 1743455320.3220422
  },
  {
    "success": false,
    "client_time": 0.005262613296508789,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc039e6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 298,
    "arrival_time": 1743455320.4142342
  },
  {
    "success": false,
    "client_time": 0.005908012390136719,
    "error": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /rag (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcc25316c0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "request_id": 299,
    "arrival_time": 1743455320.4810393
  }
]